---
Name: silverware-google
---

# Configure Page Extensions:

Page:
  extensions:
    - SilverWare\Google\Extensions\PageExtension

# Configure Content Controller:

SilverStripe\CMS\Controllers\ContentController:
  required_js:
    - silverware-google/client/dist/js/bundle.js

# Configure Site Configuration:

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - SilverWare\Google\Extensions\GoogleConfig
  google_languages:
    af: Afrikaans
    am: Amharic
    ar: Arabic
    eu: Basque
    bn: Bengali
    bg: Bulgarian
    ca: Catalan
    zh-HK: Chinese (Hong Kong)
    zh-CN: Chinese (Simplified)
    zh-TW: Chinese (Traditional)
    hr: Croatian
    cs: Czech
    da: Danish
    nl: Dutch
    en-GB: English (UK)
    en-US: English (US)
    et: Estonian
    fil: Filipino
    fi: Finnish
    fr: French
    fr-CA: French (Canadian)
    gl: Galician
    de: German
    el: Greek
    gu: Gujarati
    iw: Hebrew
    hi: Hindi
    hu: Hungarian
    is: Icelandic
    id: Indonesian
    it: Italian
    ja: Japanese
    kn: Kannada
    ko: Korean
    lv: Latvian
    lt: Lithuanian
    ms: Malay
    ml: Malayalam
    mr: Marathi
    no: Norwegian
    fa: Persian
    pl: Polish
    pt-BR: Portuguese (Brazil)
    pt-PT: Portuguese (Portugal)
    ro: Romanian
    ru: Russian
    sr: Serbian
    sk: Slovak
    sl: Slovenian
    es: Spanish
    es-419: Spanish (Latin America)
    sw: Swahili
    sv: Swedish
    ta: Tamil
    te: Telugu
    th: Thai
    tr: Turkish
    uk: Ukrainian
    ur: Urdu
    vi: Vietnamese
    zu: Zulu
